import React from "react"

export default function HeroSection() {
  return (
  <>
  <h2>MORE THAN A CINEMA </h2>

  <p>JERSEY INSPIRES ME A LOT AS A MOVIELOVER AND ALSO AS A DREAM TO BE A FILM MAKER  </p>
  <p>I ALWAYS HAS A HUGE RESPECT TOWARDS  NANI ANNA AND INSPIRED BY HIS FILMS AND PROUD THAT HE ALWYS ECOURAGES A NEW DIRECTORS AND NEW TALENTS ...
    EVERY MOVIE HE DOES WILL BE THE CELEBRATION FOR ME ...HIS SCRIPT SELECTION ALWAYS MESMIRIZES ME ..AS IA M SEEING HIM SA ANEW PERSON.. WILL BE A PROUD FAN OF NANI.. </p>
  <p>GOWTHAM THINNURU A SENSATION DIRECTOR WHO DIRECTED NOT ONLY A FILM BUT ALSO A EMOTION WHICH HAS NO AGE...EVERYTIME I SEE THE FILM..TEARS ROOL IN MY EYES ..
    THE WAY HE SHOWN NANI ANNA IN FILM IS SO CALM ...BUT THE PAIN BEHIND HIS EVERY SHOT OF SMILE TELLS EVERYTHING THAT HOW MUCH PAIN HAS ARJUN SUFFERED IN BETWEEN HIS DREAMS AND HIS RESPOSIBILITIES... 
  A MAN WHO IS NOT GOOD OR NOT FEELING WELL OR LITTLE BIT GET DISTRACTED BY HIS DREAMS WATCHES JERSEY AND MOTIVATES TROUGH THE FILM ..... </p>
  <p>ANIRUDH.... THE SOUL OF JERSEY...WHO IS THE MAN BEHIND EVERY RYTHUM EVERY PAIN BEHIND MUSIC...LITERALLY IF I HEAR JERSEY MUSIC I INSTANTLY GETS INTO THE MODE OF BEING ENJOYING ...THE MUSIC HE GAVE IS THE WORTH OF THE DEDICTION OF DIECTOR AND ARJUN THAT PUT A EMOTION MADE "JERSEY"    </p>
  <p>NANNU ADIGITHEYY "JERSEY" THARUVATHEY BAHUBALI AINA RRR AINA EDIANA </p>
  </>
  )
}