import react from "react"

export default function Salaar_hero(){

    return (
        <>
        <h2>ADRENALINE RUSH</h2>
        <h2>CPR</h2>
        <h2>DEC 22 2023</h2>

        <p>PRABHAS .....ALL KNOW HIM AS A DARLING BUT I INSPIRE HIM A LOT ... THE KIND OF CHARACTER HE HAS ...THE KIND OF HUMANITY HE HAS... THE KIND OF KINDNESS HE HAS ...I FEEL THIS INSPIRED ME A LOT ...</p>
        <p>COMING TO THE EPUHORIA OF SALAAR THE CUT OUT DOMINATES EVERY FRAME EASY...THE KIND OF BURST HE HAS SHOWN AS A COOL MAN TO MONSTER IS UNBELIEVABLE.."PRABHAS" REDEFINED MASS IN EVERY FRAME OF SALAAR...</p>
        <p>MOVIE STARTED WITH A SLOW PACE...AND EVERYTHING IS GOING WITHOUT UNDERSTAND...BUT THERE COMES COAL MINE FIGHT ....WHICH GAVE "CPR" TO THE AUDIENCE ...THEN GOES FIGHT WITH A DINOSOUR BGM..AND AFTER THE FIGHT THERE COMES AN INTERVAL WHERE IT SHOWED PRABHAS USING MACHINES WITHOUT SHOWING HIS FACE....EVERY SHOT.. COMING OUT OF THE CAR WITH AN ELEVATION...FIGHT GOES ONNN..HE USES GUNS KNIEFS..WHAT EVER...THERE ENVIELS HIS TATOOO..WHERE EVERYONE FEARS...AND THERE COMES ONE INTERVAL BANG WHICH DIMINATED WITH PURE CUTOUT...</p>
           <h3>"KANI AAA "SEAL" NI PUTTINCHINDHEYY VADUUU"</h3>
           <h3>"KHANSAR KA SALAAR"</h3>  
           <h3>VARADHA RAJAMANNAR KA SALAAR"</h3>
           <h3>SALAAR DEVARATHA RAISARR..</h3>
        <p>AFTER INTERVAL THERE COMES SOME SCENES WHERE VARADHA MEET DEVA WHERE THE BGM COMES..LITERALLY...MIND BLOWN..THERE GOES WITH INTEREST WHERE VARADHA STOPS DINOSOUR BUT HE DONT KNOW THAT WHEN DINOSOUR BURST OUT...IT IS A SCENE ..."KATERAMMA" WHERE PRABHAS GOES TO BEAST MODE ...LITERALLY WENT INTO GOD MODE WITH THIS ONE SCENE ...THERE GOES HEAVY TIGHT UNTIL CLIMAX...THERE COMES CLIMAX BANG WHERE DEVA IS SON OF DHARA ....MIND BLOWN AND ...PRASHANT NEEL PAVED A PATH TO PART 2 "SALAAR THE SHOURANGA PARVAM"</p>   
        <p>PRASHANT NEEL ....A SENSATION OF KGF...THE WAY HE SHOWED PRABHAS IS SUPERB..EVERY FRAME IN SALAAR IS A PURE WALLPAPER...THE STORY HE WROTE A STORY WAS LIKE A "INDIAN GAME OF THRONESS"... PURE FAN STUFF GIVEN BY PRASHANT NEEL...HE ABSOLUTELY MET FANS EXPECTATIONS...AFTER THE GRAND KGF SUCCESS..</p>      
        <p>RAVI BARSUR.... A HOLLYWOOD MUSIC STUFF GIVEN ....I LITERALLY DONT KNOW WHERE I WAS IN KATERAMMA SCENE AND CLIMAX SCENE BECAUSE OF RAVI BARSUR... NO ONE HAS DONE THAT JOB FOR A MOVIE FOR WHAT RAVI BARSUR HAS DONE FOR SALAAR</p>      </>
    )
}